[pyprland]
plugins = [
    "shift_monitors",
    "scratchpads"
]
[scratchpads.term]
animation = "fromBottom"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 100
